name: "OPDS"
guid: "F30880AE-3365-449E-B9E6-BF133C8401B0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opds.png"
version: "4"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Provides an OPDS book feed"
description: >
  Provides an OPDS feed for book browsing.

category: "General"
artifacts:
  - "Jellyfin.Plugin.Opds.dll"
changelog: |2-
  ### New features and improvements ###
  - Add WWW-Authenticate header to unauthorized response (#14) @crobibero
  - Add Favorites, RecentlyAdded (#12) @crobibero

  ### CI & build changes ###
  - ci: migrate to centralized Plugin CI workflows (#15) @crobibero
